# _config.yml

title: e_do_blog
logo: /assets/img/icon.png
image: /assets/img/card.png
description: e_do_blog
google_analytics: G-2KSH41991E
theme: jekyll-theme-minimal
twitter:
  username: e_do_kiriko
  card: summary
locale : JA
plugins:
  - jekyll-sitemap
